version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install rpm
      - run: sudo apt install bsdtar
      - run: make env
      - run: make build-all

