version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: rm -rf dist/*
      - run: sudo dpkg --add-architecture i386
      - run: sudo apt update
      - run: sudo apt install rpm
      - run: sudo apt install bsdtar
      - run: sudo apt install wine
      - run: sudo apt install wine32
      - run: make env
      - run: make build-all
      - run: make archive-unpacked

  make-release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: sudo npm install -g github-release-cli
      - run: make push-release

workflows:
  version: 2
  build_and_make_release:
    jobs:
      - build:
          filters:
            tags:
              only: /^.+/
      - make-release:
          requires:
            - build

