version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    filters:
      tags:
        only: /.*/
    steps:
      - checkout
      - run: rm -rf dist/*
      - run: sudo dpkg --add-architecture i386
      - run: sudo apt update
      - run: sudo apt install rpm
      - run: sudo apt install bsdtar
      - run: sudo apt install wine
      - run: sudo apt install wine32
      - run: make env
      - run: make build-all
      - run: make archive-unpacked

